spring.application.name=Arrive Wise
spring.banner.location=classpath:/banner.txt
logging.level.root=ERROR
spring.ai.model.chat=ollama
spring.ai.ollama.chat.model=mistral-small3.2
spring.ai.ollama.chat.temperature=0
spring.ai.ollama.base-url=http://localhost:11434
    